# ===== КРИТИЧНО для ARM: свой aarch64 aapt2 вместо x86_64 из Maven =====
android.aapt2FromMavenOverride=/root/bin/aapt2

# ===== Память/стабильность внутри proot =====
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configureondemand=false
org.gradle.vfs.watch=false
org.gradle.workers.max=2

# ===== Kotlin: компилировать в том же процессе (без отдельного демона) =====
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
kotlin.daemon.jvmargs=-Xmx1536m

# ===== Android =====
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=false

android.suppressUnsupportedCompileSdk=37,38
# отключаем NDK-проверки, если NDK не установлен
android.native.buildOutput=quiet
